import Dom from '../dispatcher/dom';
import Dispatcher from '../dispatcher/index';
import { IVideoKernelConstructor } from '../kernels/base';
import { SupportedKernelType, UserConfig, UserKernelsConfig } from '../typings/base';
export default class VideoConfig {
    autoload: boolean;
    autoplay: boolean;
    box: 'mp4' | 'hls' | 'flv' | '';
    changeWatchable: boolean;
    controls: boolean;
    crossOrigin: string | void;
    defaultMuted: boolean;
    defaultPlaybackRate: number;
    disableRemotePlayback: boolean;
    dispatcher: Dispatcher;
    dom: Dom;
    height: string | number | void;
    inited: boolean;
    isLive: boolean;
    kernels: UserKernelsConfig;
    loop: boolean;
    muted: boolean;
    needToLoadSrc: boolean;
    playbackRate: number;
    playsInline: boolean;
    poster: string;
    preload: 'none' | 'auto' | 'metadata' | '';
    preset: {
        [key in SupportedKernelType]?: IVideoKernelConstructor;
    };
    presetConfig: any;
    src: string;
    volume: number;
    width: string | number | void;
    x5VideoOrientation: 'landscape' | 'portrait' | undefined;
    x5VideoPlayerFullscreen: boolean;
    x5VideoPlayerType: 'h5' | undefined;
    xWebkitAirplay: boolean;
    constructor(dispatcher: Dispatcher, config: UserConfig);
    init(): void;
}
