export const videoEvents = [
  'abort',
  'canplay',
  'canplaythrough',
  'durationchange',
  'emptied',
  'encrypted',
  'ended',
  'error',
  'interruptbegin',
  'interruptend',
  'loadeddata',
  'loadedmetadata',
  'loadstart',
  'mozaudioavailable',
  'pause',
  'play',
  'playing',
  'progress',
  'ratechange',
  'seeked',
  'seeking',
  'stalled',
  'suspend',
  'timeupdate',
  'volumechange',
  'waiting'
];
export const videoReadOnlyProperties = [
  'buffered',
  'currentSrc',
  'duration',
  'error',
  'ended',
  'networkState',
  'paused',
  'readyState',
  'seekable',
  'sinkId',
  'controlsList',
  'tabIndex',
  'dataset',
  'offsetHeight',
  'offsetLeft',
  'offsetParent',
  'offsetTop',
  'offsetWidth'
];
export const domEvents = [
  'beforeinput',
  'blur',
  'click',
  'compositionend',
  'compositionstart',
  'compositionupdate',
  'dblclick',
  'focus',
  'focusin',
  'focusout',
  'input',
  'keydown',
  'keypress',
  'keyup',
  'mousedown',
  'mouseenter',
  'mouseleave',
  'mousemove',
  'mouseout',
  'mouseover',
  'mouseup',
  'resize',
  'scroll',
  'select',
  'wheel',
  'fullscreenchange',
  'webkitfullscreenchange',
  'mozfullscreenchange',
  'msfullscreenchange',
  'contextmenu'
];
export const selfProcessorEvents = [
  'silentLoad',
  'fullScreen'
];
export const kernelMethods = [
  'play',
  'pause',
  'seek'
];
export const dispatcherMethods = [
  'load'
];
export const kernelEvents = [
  'mediaInfo'
];
export const domMethods = [
  'focus',
  'fullScreen',
  'requestFullScreen',
  'exitFullScreen'
];
export const videoMethods = [
  'canPlayType',
  'captureStream',
  'setSinkId'
];
